# Generated by Django 6.0.2 on 2026-03-19 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(max_length=50)),
                ('pet_breed', models.CharField(blank=True, max_length=50, null=True)),
                ('pet_color', models.CharField(blank=True, max_length=50, null=True)),
                ('pet_image', models.ImageField(blank=True, null=True, upload_to='pet_report_images/')),
                ('pet_status', models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], default='Lost', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('admin_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], default='Pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.user')),
            ],
            options={
                'db_table': 'pet_report',
            },
        ),
    ]
