# Generated by Django 6.0.2 on 2026-03-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petreport',
            old_name='description',
            new_name='admin_comment',
        ),
        migrations.RenameField(
            model_name='petreport',
            old_name='user',
            new_name='reviewed_by',
        ),
        migrations.AddField(
            model_name='petreport',
            name='reviewed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
