# Generated by Django 6.0.2 on 2026-03-08 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_description_petreport_admin_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petreport',
            name='contact_number',
        ),
    ]
