# Generated by Django 6.0.2 on 2026-03-08 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PetReport',
        ),
    ]
